### ISSUE TITLE
branches a|b matching?

### ISSUE THREAD

**Issue by Rukenshia** [starkandwayne/git-multibranch-resource#8]
Hello,

we're trying to run both `feature/.*` and `bugfix/.*` branches through the same pipeline but I can't get the resource to find any new versions.

I've tried various regex, such as `(feature|bugfix)/.*` (with variations of escaping the parens and pipe), `feature/.*|bugfix/.*` but nothing seems to work. The documentation just says 'Uses grep-style regular expression syntax`).

Running grep with i.e. this regex yields a correct result:
```
echo "feature/some-awesome-feature" | grep -e "\(feature\|bugfix\)/.*"
=> feature/some-awesome-feature
```

Any help would be very much appreciated.

**Comment by Rukenshia** [comment]
@geofffranks `ignore_branches: '(master|develop)'` also does not work at all, I am seeing builds run for the master and develop branch too.

**Comment by geofffranks** [comment]
@Rukenshia i'm not too familiar with this resource, but @dennisjbell might be able to help out

**Comment by jhunt** [comment]
@Rukenshia what happens if you run this ugly monster of a shell pipeline?

```
echo "$(git branch -rv --no-abbrev | awk '{print $2 ":" $1}' |\
  grep -e '^[0-9a-f]\{40\}:' |\
  sort -t: -k1 |\
  grep ':origin/' |\
  sed -e 's/:origin\//:/' |\
  tr ' ' "\n")" | grep -E ":(feature|bugfix)/.*$"
```

and also,

```
echo "$(git branch -rv --no-abbrev | awk '{print $2 ":" $1}' |\
  grep -e '^[0-9a-f]\{40\}:' |\
  sort -t: -k1 |\
  grep ':origin/' |\
  sed -e 's/:origin\//:/' |\
  tr ' ' "\n")" | grep -v -E ":(master|develop)$"
```

**Comment by Rukenshia** [comment]
Then I get a (pretty long) list of branch names that include feature/ or
bugfix in the format of `hash:branchname`, like the usual output of the
multibranch resource. So locally it works fine for me, just not in our
pipeline.

James Hunt <notifications@github.com> schrieb am Fr., 9. Juni 2017 um
07:17 Uhr:

**Comment by jhunt** [comment]
That would be because our pipeline hasn't promoted the most recent 9 commits on master.  I verified that `cfcommunity/git-multibranch-resource:latest` does not include the `-E` flags to grep.

I went ahead and promoted `:latest-edge:` to `:latest`, so you should be good to go now (assuming concourse pulls in the update)

**Comment by Rukenshia** [comment]
can confirm that it works now, thanks!
